/*******************************************************************************
*
*  McStas, neutron ray-tracing package
*  Copyright(C) 2007 Risoe National Laboratory.
*
* %I
* Written by: Daniel Lomholt Christensen
* Date: 08.10.25
* Origin: University of Copenhagen / ACTNXT project
*
* Component for including 3D mesh in Union geometry
*
* %D
* Part of the Union components, a set of components that work together and thus
*  separates geometry and physics within McStas.
* The use of this component requires other components to be used.
*
* 1) One specifies a number of processes using process components
* 2) These are gathered into material definitions using Union_make_material
* 3) Geometries are placed using Union_box/cylinder/sphere/mesh, assigned a material
* 4) A Union_master component placed after all the above
*
* Only in step 4 will any simulation happen, and per default all geometries
*  defined before this master, but after the previous will be simulated here.
*
* There is a dedicated manual available for the Union_components
*
* The mesh component loads a 3D off file as the geometry. The mesh geometry
* can not yet be overlapped with the basic geometries (sphere, cylinder, box, cone),
* but can be overlapped with other mesh geometries.
*
* It is allowed to overlap components, but it is not allowed to have two
*  parallel planes that coincides. This will crash the code on run time.
*
*
*
* %P
* INPUT PARAMETERS:
* filename: [str] Name of off file that contains the 3D geometry
* material_string: [string]  material name of this volume, defined using Union_make_material
* priority:   [1]  priotiry of the volume (can not be the same as another volume) A high priority is on top of low.
* p_interact: [1]  probability to interact with this geometry [0-1]
* visualize:  [1]  set to 0 if you wish to hide this geometry in mcdisplay
* number_of_activations: [1]  Number of subsequent Union_master components that will simulate this geometry
* mask_string: [string]      Comma seperated list of geometry names which this geometry should mask
* mask_setting: [string]     "All" or "Any", should the masked volume be simulated when the ray is in just one mask, or all.
* target_index:  [1]    Focuses on component a component this many steps further in the component sequence
* target_x:      [m]
* target_y:      [m] Position of target to focus at
* target_z:      [m]
* focus_aw:      [deg] horiz. angular dimension of a rectangular area
* focus_ah:      [deg] vert. angular dimension of a rectangular area
* focus_xw:      [m]   horiz. dimension of a rectangular area
* focus_xh:      [m]   vert. dimension of a rectangular area
* focus_r:       [m]   focusing on circle with this radius
* init:          [string] name of Union_init component (typically "init", default)
*
* CALCULATED PARAMETERS:
*
* %L
*
* %E
******************************************************************************/

DEFINE COMPONENT Union_mesh_off

SETTING PARAMETERS(string filename = 0,
   string material_string=0,
   priority, 
   visualize=1, 
   int target_index=0, 
   target_x=0,
   target_y=0,
   target_z=0,
   focus_aw=0,
   focus_ah=0,
   focus_xw=0,
   focus_xh=0,
   focus_r=0,
   p_interact=0,
   string mask_string=0,
   string mask_setting=0,
   number_of_activations=1,
   string init="init")


/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */

//=============================================================================
//                            SHARE SECTION
//=============================================================================
SHARE
%{
#ifndef Union
#error "The Union_init component must be included before this Union_mesh component"
#endif

#ifndef ANY_GEOMETRY_DETECTOR_DECLARE
    #define ANY_GEOMETRY_DETECTOR_DECLARE dummy
    //struct pointer_to_global_geometry_list global_geometry_list = {0,NULL};
#endif


int mesh_is_closed(int n_verts, int n_faces, int n_edges){
   if (n_verts - n_edges + n_faces ==2){
      return 1;
   }
   return 0;
}


void find_coords(){
   printf("Not working");
}

Coords get_coords_from_string(char* line){
   Coords vert_coords = coords_set(1,2,1);
   return vert_coords;
}


void mcdisplay_mesh_function(struct lines_to_draw *lines_to_draw_output,
                             int index, 
                             struct geometry_struct **Geometries,
                             int number_of_volumes) {
   printf("Running Mcdisplay now, I swear!\n");
}


struct pointer_to_1d_coords_list mesh_shell_points(struct geometry_struct *geometry,int max_number_of_points) {



}


void initialize_mesh_geometry_from_main_component(struct geometry_struct *mesh) {

}

%}

//=============================================================================
//                            DECLARE SECTION
//=============================================================================
DECLARE
%{
// Needed for transport to the main component
struct global_geometry_element_struct global_geometry_element;

int loop_index;
int loop_2_index;
int material_index;

// Volume struct contains name, geometry struct, physics struct
// loggers struct and absorption loggers struct.
struct Volume_struct mesh_vol;

// TODO mesh storage currently allocates crazy amounts of data.
// Make it dynamically allocated instead
// Mesh storage contains 
struct mesh_storage mesh_storage;
%}

INITIALIZE
%{
// Initializes the focusing system for this volume including input sanitation.
focus_initialize(&mesh_vol.geometry, 
      POS_A_COMP_INDEX(INDEX_CURRENT_COMP+target_index),
      POS_A_CURRENT_COMP,
      ROT_A_CURRENT_COMP,
      target_index,
      target_x,
		target_y,
		target_z,
		focus_aw,
		focus_ah,
		focus_xw,
		focus_xh,
		focus_r,
		NAME_CURRENT_COMP);



if (_getcomp_index(init) < 0) {
   fprintf(stderr,"Union_mesh:%s: Error identifying Union_init component,"
           "%s is not a known component name.\n",NAME_CURRENT_COMP, init);
exit(-1);
}
struct pointer_to_global_material_list *global_material_list = COMP_GETPAR3(
      Union_init,
		init,
		global_material_list);

// Use sanitation
#ifdef MATERIAL_DETECTOR
if (global_material_list->num_elements == 0) {
  // Here if the user have defined a material, but only after this material
   printf("\nERROR: Need to define a material using Union_make_material"
          " before using a Union geometry component. \n");
  printf("%s was defined before first use of Union_make_material.\n",NAME_CURRENT_COMP);
  exit(1);
}

#endif
#ifndef MATERIAL_DETECTOR
printf("\nERROR: Need to define a material using Union_make_material"
       " before using a Union geometry component. \n");
  exit(1);
#endif


mesh_vol.geometry.is_masked_volume = 0;
mesh_vol.geometry.is_exit_volume = 0;
mesh_vol.geometry.is_mask_volume = 0;

struct pointer_to_global_geometry_list *global_geometry_list = COMP_GETPAR3(Union_init,
		init,
		global_geometry_list);
//==============================================================================
//                         Find out what this component masks
//==============================================================================



// Read the material input, or if it lacks, use automatic linking.
if (mask_string && 
   strlen(mask_string) && 
   strcmp(mask_string, "NULL") && 
   strcmp(mask_string, "0")) {
    // A mask volume is used to limit the extend of other volumes, 
   // called the masked volumes. These are specified in the mask_string.
    // In order for a ray to enter a masked volume, 
   // it needs to be both in the region covered by that volume AND the mask volume.
    // When more than
    mesh_vol.geometry.mask_mode = 1; // Default mask mode is ALL
    if (mask_setting && strlen(mask_setting) && strcmp(mask_setting,
		"NULL") && strcmp(mask_setting, "0")) {
      if (strcmp(mask_setting,"ALL") == 0 || strcmp(mask_setting,"All") == 0) {
         mesh_vol.geometry.mask_mode = 1;
      }
      else if (strcmp(mask_setting,"ANY") == 0 || strcmp(mask_setting,"Any") == 0) {
         mesh_vol.geometry.mask_mode = 2;
      }
      else {
         printf("The mask_mode of component %s is set to %s,"
                " but must be either ALL or ANY.\n",
                NAME_CURRENT_COMP,mask_setting);
         exit(1);
        }
    }
    
    int found_geometries = 0;
    for (loop_index=0;loop_index<global_geometry_list->num_elements;loop_index++) {
        // Add mask list

        if (1 == manual_linking_function(global_geometry_list->elements[loop_index].name,mask_string)) {
            add_element_to_int_list(&mesh_vol.geometry.mask_list,global_geometry_list->elements[loop_index].component_index);
            add_element_to_int_list(&global_geometry_list->elements[loop_index].Volume->geometry.masked_by_list,INDEX_CURRENT_COMP);
            global_geometry_list->elements[loop_index].Volume->geometry.is_masked_volume = 1;
            if (mesh_vol.geometry.mask_mode == 2)
                global_geometry_list->elements[loop_index].Volume->geometry.mask_mode = 2;
            if (mesh_vol.geometry.mask_mode == 1) {
                if (global_geometry_list->elements[loop_index].Volume->geometry.is_masked_volume == 1 && global_geometry_list->elements[loop_index].Volume->geometry.mask_mode != 2)
                    // If more than one mask is added to one volume, the ANY mode overwrites the (default) ALL mode.
                    global_geometry_list->elements[loop_index].Volume->geometry.mask_mode = 1;
            }
            
            found_geometries = 1;
        }
    }
    if (found_geometries == 0) {
      printf("The mask_string in geometry: "
             "%s did not find any of the specified volumes in the mask_string "
             "%s \n",NAME_CURRENT_COMP,mask_string);
        exit(1);
    }
    mesh_vol.p_physics = malloc(sizeof(struct physics_struct));
    mesh_vol.p_physics->is_vacuum = 0; // Makes this volume a vacuum
    mesh_vol.p_physics->number_of_processes = (int) 0; // Should not be used.
    mesh_vol.p_physics->my_a = 0; // Should not be used.
    sprintf(mesh_vol.p_physics->name,"Mask");
    mesh_vol.geometry.is_mask_volume = 1;
    
    
// Read the material input, or if it lacks, use automatic linking.
} else if (material_string 
   && strlen(material_string) 
   && strcmp(material_string, "NULL") 
   && strcmp(material_string, "0")) {
    // A geometry string was given, use it to determine which material
    if (0 == strcmp(material_string,"vacuum") 
     || 0 == strcmp(material_string,"Vacuum")) {
        // One could have a global physics struct for vacuum instead of creating one for each
        mesh_vol.p_physics = malloc(sizeof(struct physics_struct));
        mesh_vol.p_physics->is_vacuum = 1; // Makes this volume a vacuum
        mesh_vol.p_physics->number_of_processes = (int) 0;
        mesh_vol.p_physics->my_a = 0; // Should not be used.
        sprintf(mesh_vol.p_physics->name,"Vacuum");
    } else if (0 == strcmp(material_string,"exit") 
            || 0 == strcmp(material_string,"Exit")) {
        // One could have a global physics struct for exit instead of creating one for each
        mesh_vol.p_physics = malloc(sizeof(struct physics_struct));
        mesh_vol.p_physics->is_vacuum = 1; // Makes this volume a vacuum
        mesh_vol.p_physics->number_of_processes = (int) 0;
        mesh_vol.p_physics->my_a = 0; // Should not be used.
        mesh_vol.geometry.is_exit_volume = 1;
        sprintf(mesh_vol.p_physics->name,"Exit");
    } else {
        for (loop_index=0;loop_index<global_material_list->num_elements;loop_index++) {
          if (0 == strcmp(material_string,global_material_list->elements[loop_index].name)) {
            mesh_vol.p_physics = global_material_list->elements[loop_index].physics;
            break;
          }
          if (loop_index == global_material_list->num_elements-1) {
            printf("\n");
            printf("ERROR: The material string \"%s\" in Union geometry \"%s\""
                   " did not match a specified material. \n",material_string,NAME_CURRENT_COMP);
            printf("       The materials available at this point"
                   " (need to be defined before the geometry): \n");
            for (loop_index=0;loop_index<global_material_list->num_elements;loop_index++)
              printf("         %s\n",global_material_list->elements[loop_index].name);
            printf("\n");
            printf("       It is also possible to use one of the defualt materials avaiable: \n");
            printf("           Vacuum (for a Volume without scattering or absorption)\n");
            printf("           Exit (for a Volume where the ray exits the component if it enters)\n");
            printf("           Mask (for a Volume that masks existing volumes specified in the mask_string\n");
            exit(1);
          }
        }
    }
} else {
    // Automatic linking, simply using the last defined material.
    #ifndef MATERIAL_DETECTOR
        printf("Need to define a material before the geometry to use automatic linking %s.\n",NAME_CURRENT_COMP);
        exit(1);
    #endif
    mesh_vol.p_physics = global_material_list->elements[global_material_list->num_elements-1].physics;
}
//==============================================================================
//                       READ FIle   
//==============================================================================
// Read input file and put into storage 
// test 2
printf("\nSTART read file: ");
int n_verts, n_faces, n_edges;
FILE *fp;
fp = fopen(filename,"r");
// TODO: Make tests to verify the contents of FILE
int n_lines;
char buffer[250];
printf("\ntest1");
n_lines = 0;
while (fgets(buffer, sizeof(buffer), fp)) {
   if (!strncmp(buffer, "#",1)){
      printf("\nFound comment");
      continue;
   }
   if (n_lines == 1){
      // in .off files the second line contains faces, vertices and edges
      sscanf(buffer,"%d %d %d", &n_verts, &n_faces, &n_edges);
      break;
   }
   ++n_lines;
}
fclose(fp);  
printf("\nN vertices = %d", n_verts);
printf("\nN faces = %d", n_faces);
printf("\nN Edges = %d", n_edges);
// Using the Euler-Poincare characteristic, we check if the mesh is closed
// To do this, we count the number of edges (unique vertice pairs)
Coords verts[n_verts];
fp = fopen(filename,"r");
n_lines = 0;
while (fgets(buffer, sizeof(buffer), fp)) {
   if (!strncmp(buffer, "#",1)){
      printf("\nFound comment");
      continue;
   }
   // We are only interested in vertices right now, so stop reading after that
   if (n_lines>(n_verts+2)){
      break;
   }
   
   sscanf(buffer,"%f %f %f", 
          &verts[n_lines].x, &verts[n_lines].y, &verts[n_lines].z);
   ++n_lines;

}


fclose(fp);





exit(0);

	// int n_facets = (n_lines-2)/7;
	//
	// printf("\n done");
	// //printf("\n n_facets: %i",n_facets);
	//
	//
	//    char *line = NULL;
	//    size_t len = 0;
	// char dest[9]; // 8 chars + terminator
	// int iter = 0; int counter = 0;
	//    ssize_t read;
	//
	// Coords normal[n_facets+1];
	// Coords v1[n_facets+1];
	// Coords v2[n_facets+1];
	// Coords v3[n_facets+1];
	//
	// //#include "MeshFunctions/get_coords_from_string.c"
	// printf("\nTEST n_facets = %i\n",n_facets);
	// Coords fromString;
	//    fp = fopen(filename, "r");
	//    if (fp == NULL)
	//        exit(EXIT_FAILURE);
	//    while ((read = getline(&line, &len, fp)) != -1) {
	// 	//printf("______________________-----NEW------_____________________\n");
	// 	//printf("%s\n", line);
	//
	// 		if (iter==1){
	// 			if (line[0] == 101){
	// 				//printf("\nDone reading file\n");
	// 			}else{
	//
	// 				// Normal vector
	// 				fromString = get_coords_from_string(line);
	// 				normal[counter]=fromString;
	//
	// 				//printf("\n normal: [%i]: normal[%i] = [%f,%f,%f] \n",iter,counter,normal[counter].x,normal[counter].y,normal[counter].z);
	// 			}
	// 		}
	// 		if (iter==3){
	// 			fromString = get_coords_from_string(line);
	// 			v1[counter]=fromString;
	// 			//printf("\n v1 [%i]: v1[%i] = [%f,%f,%f] \n",iter,counter,v1[counter].x,v1[counter].y,v1[counter].z);
	// 		}
	// 		if (iter==4){
	// 			fromString = get_coords_from_string(line);
	// 			v2[counter]=fromString;
	// 			//printf("\n v2 [%i]: v2[%i] = [%f,%f,%f] \n",iter,counter,v2[counter].x,v2[counter].y,v2[counter].z);
	// 		}
	// 		if (iter==5){
	// 			fromString = get_coords_from_string(line);
	// 			v3[counter]=fromString;
	// 			//printf("\n v3 [%i]: v3[%i] = [%f,%f,%f] \n",iter,counter,v3[counter].x,v3[counter].y,v3[counter].z);
	//
	// 		}
	// 		if (iter==7){
	// 			iter = 0;
	// 			counter ++;
	// 		}
	// 	//printf("\n TESTTESTTEST:  [%f,%f,%f] \n",mesh_storage.poligon_list[counter].normal.x,mesh_storage.poligon_list[counter].normal.y,mesh_storage.poligon_list[counter].normal.z);
	//
	// 	iter++; 
	//    }
	//
	//    fclose(fp);
	//
	// int i;
	//
	// // Transform coordinate (translate then rotate)
	// printf("\n\nPOS_A_CURRENT_COMP [%f,%f,%f]",POS_A_CURRENT_COMP.x,POS_A_CURRENT_COMP.y,POS_A_CURRENT_COMP.z);
	// for (i = 0 ; i < counter ; i++ ){
		// run through existing arrays without creating new ones. This is a very bad habbit!  PLZ fix
		
        /*
		// v1
		v1[i].x = v1[i].x + POS_A_CURRENT_COMP.x;
		v1[i].y = v1[i].y + POS_A_CURRENT_COMP.y;
		v1[i].z = v1[i].z + POS_A_CURRENT_COMP.z;
		//v1[i] = rot_apply(mesh_vol.geometry.transpose_rotation_matrix,v1[i]);

		// v2
		v2[i].x = v2[i].x + POS_A_CURRENT_COMP.x;
		v2[i].y = v2[i].y + POS_A_CURRENT_COMP.y;
		v2[i].z = v2[i].z + POS_A_CURRENT_COMP.z;
		//v2[i] = rot_apply(mesh_vol.geometry.transpose_rotation_matrix,v2[i]);
		
		// v3
		v3[i].x = v3[i].x + POS_A_CURRENT_COMP.x;
		v3[i].y = v3[i].y + POS_A_CURRENT_COMP.y;
		v3[i].z = v3[i].z + POS_A_CURRENT_COMP.z;
		//v3[i] = rot_apply(mesh_vol.geometry.transpose_rotation_matrix,v3[i]);
        */
        
        /*
        // v1
        v1[i].x = v1[i].x + POS_A_CURRENT_COMP.x;
        v1[i].y = v1[i].y + POS_A_CURRENT_COMP.y;
        v1[i].z = v1[i].z + POS_A_CURRENT_COMP.z;
        //v1[i] = rot_apply(mesh_vol.geometry.transpose_rotation_matrix,v1[i]);

        // v2
        v2[i].x = v2[i].x + POS_A_CURRENT_COMP.x;
        v2[i].y = v2[i].y + POS_A_CURRENT_COMP.y;
        v2[i].z = v2[i].z + POS_A_CURRENT_COMP.z;
        //v2[i] = rot_apply(mesh_vol.geometry.transpose_rotation_matrix,v2[i]);
        
        // v3
        v3[i].x = v3[i].x + POS_A_CURRENT_COMP.x;
        v3[i].y = v3[i].y + POS_A_CURRENT_COMP.y;
        v3[i].z = v3[i].z + POS_A_CURRENT_COMP.z;
        */
		
   //}
	//printf("\n TEST inf v1 is long enough! i = %i , n_facets = %i, counter = %i \n",i,n_facets,counter);
	
	// Create bounding sphere using Ritter [https://en.wikipedia.org/wiki/Bounding_sphere#cite_note-Ritter1990-2]
	//  Ritter, Jack (1990), "An efficient bounding sphere", in Glassner, Andrew S., Graphics Gems, San Diego, CA, US: Academic Press Professional, Inc., pp. 301–303, ISBN 0-12-286166-3
	// double max_dist=0;
	//
	// Coords B_sphere_x = v1[0];
	// Coords B_sphere_y = B_sphere_x ;
	// for (i = 1 ; i < counter ; i++ ){
	// 	if (sqrt(v1[0].x-v1[i].x+v1[0].y-v1[i].y+v1[0].z-v1[i].z) > max_dist){
	// 		max_dist = sqrt(v1[0].x-v1[i].x+v1[0].y-v1[i].y+v1[0].z-v1[i].z);
	// 		B_sphere_y = v1[i];
	// 	}
	// 	if (sqrt(v1[0].x-v2[i].x+v1[0].y-v2[i].y+v1[0].z-v2[i].z) > max_dist){
	// 		max_dist = sqrt(v1[0].x-v2[i].x+v1[0].y-v2[i].y+v1[0].z-v2[i].z);
	// 		B_sphere_y = v2[i];
	// 	}
	// 	if (sqrt(v1[0].x-v3[i].x+v1[0].y-v3[i].y+v1[0].z-v3[i].z) > max_dist){
	// 		max_dist = sqrt(v1[0].x-v3[i].x+v1[0].y-v3[i].y+v1[0].z-v3[i].z);
	// 		B_sphere_y = v3[i];
	// 	}
	// }
	// Coords B_sphere_z = B_sphere_y ;
	// max_dist=0;
	// for (i = 1 ; i < counter ; i++ ){
	// 	if (sqrt(pow(B_sphere_y.x-v1[i].x,2) + pow(B_sphere_y.y-v1[i].y,2) + pow(B_sphere_y.z-v1[i].z,2)) > max_dist){
	// 		max_dist = sqrt(pow(B_sphere_y.x-v1[i].x,2) + pow(B_sphere_y.y-v1[i].y,2) + pow(B_sphere_y.z-v1[i].z,2));
	// 		B_sphere_z = v1[i];
	// 	}
	// 	if (sqrt(pow(B_sphere_y.x-v2[i].x,2) + pow(B_sphere_y.y-v2[i].y,2) + pow(B_sphere_y.z-v2[i].z,2)) > max_dist){
	// 		max_dist = sqrt(pow(B_sphere_y.x-v2[i].x,2) + pow(B_sphere_y.y-v2[i].y,2) + pow(B_sphere_y.z-v2[i].z,2));
	// 		B_sphere_z = v2[i];
	// 	}
	// 	if (sqrt(pow(B_sphere_y.x-v3[i].x,2) + pow(B_sphere_y.y-v3[i].y,2) + pow(B_sphere_y.z-v3[i].z,2)) > max_dist){
	// 		max_dist = sqrt(pow(B_sphere_y.x-v3[i].x,2) + pow(B_sphere_y.y-v3[i].y,2) + pow(B_sphere_y.z-v3[i].z,2));
	// 		B_sphere_z = v3[i];
	// 	}
	// }
	//
	// double tmp_Radius = sqrt(pow(B_sphere_y.x-B_sphere_z.x,2.0) + pow(B_sphere_y.y-B_sphere_z.y,2.0) + pow(B_sphere_y.z-B_sphere_z.z,2.0))/2;
	// Coords bbcenter = coords_set((B_sphere_y.x+B_sphere_z.x)/2 , (B_sphere_y.y+B_sphere_z.y)/2 , (B_sphere_y.z+B_sphere_z.z)/2);
	// mesh_storage.Bounding_Box_Center = bbcenter;
	// for (i = 0 ; i < counter ; i++ ){
	// 	if (sqrt(pow(bbcenter.x-v1[i].x,2.0) + pow(bbcenter.y-v1[i].y,2.0) + pow(bbcenter.z-v1[i].z,2.0)) > tmp_Radius){
	// 		tmp_Radius = sqrt(pow(bbcenter.x-v1[i].x,2.0) + pow(bbcenter.y-v1[i].y,2.0) + pow(bbcenter.z-v1[i].z,2.0));
	// 	}
	// 	if (sqrt(pow(bbcenter.x-v2[i].x,2.0) + pow(bbcenter.y-v2[i].y,2.0) + pow(bbcenter.z-v2[i].z,2.0)) > tmp_Radius){
	// 		tmp_Radius = sqrt(pow(bbcenter.x-v2[i].x,2.0) + pow(bbcenter.y-v2[i].y,2.0) + pow(bbcenter.z-v2[i].z,2.0));
	// 	}
	// 	if (sqrt(pow(bbcenter.x-v3[i].x,2.0) + pow(bbcenter.y-v3[i].y,2.0) + pow(bbcenter.z-v3[i].z,2.0)) > tmp_Radius){
	// 		tmp_Radius = sqrt(pow(bbcenter.x-v3[i].x,2.0) + pow(bbcenter.y-v3[i].y,2.0) + pow(bbcenter.z-v3[i].z,2.0));
	// 	}
	//
	// }
	// mesh_storage.Bounding_Box_Radius = tmp_Radius;
	// printf("\n__________________________________\n BOUNDING BOX: \n\t Center = [%f , %f , %f]\n\t Radius = %f\n__________________________________\n", mesh_storage.Bounding_Box_Center.x,mesh_storage.Bounding_Box_Center.y,mesh_storage.Bounding_Box_Center.z,mesh_storage.Bounding_Box_Radius);
	//
	//
	//
	//
	// // Convert to double arrays for further parsing (Coord has problems here - might be possible to do much faster!!)
	// // Seriously not optimal... plz fix
	// double v1_x[counter];
	// double v1_y[counter];
	// double v1_z[counter];
	// double v2_x[counter];
	// double v2_y[counter];
	// double v2_z[counter];
	// double v3_x[counter];
	// double v3_y[counter];
	// double v3_z[counter];
	// double normal_x[counter];
	// double normal_y[counter];
	// double normal_z[counter];
	//
	//
	//
	// for (i = 0 ; i < counter ; i++ ){
		/*
		v1_x[i] = v1[i].x;
		v1_y[i] = v1[i].y;
		v1_z[i] = v1[i].z;
		
		v2_x[i] = v2[i].x;
		v2_y[i] = v2[i].y;
		v2_z[i] = v2[i].z;
		
		v3_x[i] = v3[i].x;
		v3_y[i] = v3[i].y;
		v3_z[i] = v3[i].z;
		
		normal_x[i] = normal[i].x;
		normal_y[i] = normal[i].y;
		normal_z[i] = normal[i].z;
		*/
		// mesh_storage.v1_x[i] = v1[i].x;
		// mesh_storage.v1_y[i] = v1[i].y;
		// mesh_storage.v1_z[i] = v1[i].z;
		//
		// mesh_storage.v2_x[i] = v2[i].x;
		// mesh_storage.v2_y[i] = v2[i].y;
		// mesh_storage.v2_z[i] = v2[i].z;
		//
		// mesh_storage.v3_x[i] = v3[i].x;
		// mesh_storage.v3_y[i] = v3[i].y;
		// mesh_storage.v3_z[i] = v3[i].z;
		//
		// mesh_storage.normal_x[i] = normal[i].x;
		// mesh_storage.normal_y[i] = normal[i].y;
		// mesh_storage.normal_z[i] = normal[i].z;
		
		//printf("\n v2 [%i]: v2[%i] = [%f,%f,%f] \n",iter,v2_x[i],v2_y[i],v2_z[i]);
	// }

// check if this is a cylinder and add coordinates of tip if it is a mesh

// mesh_storage.counter = counter;
// mesh_storage.n_facets = n_facets;


// sprintf(mesh_vol.name,"%s",NAME_CURRENT_COMP);
// sprintf(mesh_vol.geometry.shape,"mesh");
// mesh_vol.geometry.priority_value = priority;
// Currently the coordinates will be in absolute space.
// mesh_vol.geometry.center = POS_A_CURRENT_COMP;
//
// mesh_vol.geometry.geometry_p_interact = p_interact;
//
//
//
// mesh_vol.geometry.visualization_on = visualize;
// mesh_vol.geometry.geometry_parameters.p_mesh_storage = &mesh_storage;
// mesh_vol.geometry.within_function = &r_within_mesh;
// mesh_vol.geometry.intersect_function = &sample_mesh_intersect;
// mesh_vol.geometry.mcdisplay_function = &mcdisplay_mesh_function;
// mesh_vol.geometry.shell_points = &mesh_shell_points;
// mesh_vol.geometry.initialize_from_main_function = &initialize_mesh_geometry_from_main_component;
// mesh_vol.geometry.process_rot_allocated = 0;
// mesh_vol.geometry.copy_geometry_parameters = &allocate_mesh_storage_copy;
// rot_copy(mesh_vol.geometry.rotation_matrix,ROT_A_CURRENT_COMP);
// rot_transpose(ROT_A_CURRENT_COMP,mesh_vol.geometry.transpose_rotation_matrix);
//
//
// // Initialize loggers
// mesh_vol.loggers.num_elements = 0;
//
// // packing the information into the global_geometry_element, which is then included in the global_geometry_list.
// sprintf(global_geometry_element.name,"%s",NAME_CURRENT_COMP);
// global_geometry_element.activation_counter = number_of_activations;
// global_geometry_element.component_index = INDEX_CURRENT_COMP;
// global_geometry_element.Volume = &mesh_vol; // Would be nicer if this m was a pointer, now we have the (small) data two places
// add_element_to_geometry_list(global_geometry_list,global_geometry_element);
%}

TRACE
%{
%}

END

