/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright (C) 1997-2008, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Component: Annulus
*
* %I
* Written by: E. Farhi
* Date: June 23rd 2009
* Origin: ILL
* Modified by: E. Farhi, based on Incoherent
*
* A geometric shape without effect on neutron, for instrument display purpose.
*
* %D
* An inactive geometrical shape (annulus), for drawing purposes only.
* Derived from the <b><a href="Shape.html">Shape</a></b> component
*
* Example: Annulus(radius=0.05, yheight=0.1)
*
* %P
* INPUT PARAMETERS:
* radius: [m]      Outer radius of geometry in (x,z) plane
* outer_radius: [m] Outer radius of geometry in (x,z) plane
* inner_radius: [m] Inner radius of geometry in (x,z) plane
* xwidth: [m]      Horiz. dimension of geometry as a width
* yheight: [m]     Vert. 
* zdepth: [m]      Depth dimension of geometry
*
* %L
* mcdoc page of <a href="Shape.html">Shape</a></b> component
*
* %E
*******************************************************************************/

DEFINE COMPONENT Annulus

SETTING PARAMETERS (outer_radius=0,inner_radius=0,radius=0, xwidth=0, yheight=0, zdepth=0)

/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */

SHARE
%{
%}

DECLARE
%{
%}

INITIALIZE
%{
  /* */
%}


TRACE %{
  /* component Annulus does nothing */
%}

MCDISPLAY
%{
    mcdis_annulus(0,0,0,outer_radius, inner_radius, 0,1,0);
%}

END
