/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright (C) 1997-2008, All rights reserved
*         Risoe National Laboratory, Roskilde, Denmark
*         Institut Laue Langevin, Grenoble, France
*
* Component: Disc
*
* %I
* Written by: E. Farhi
* Date: June 23rd 2009
* Origin: ILL
* Modified by: E. Farhi, based on Incoherent
*
* A geometric shape without effect on neutron, for instrument display purpose.
*
* %D
* An inactive geometrical shape (annulus), for drawing purposes only.
* Derived from the <b><a href="Shape.html">Shape</a></b> component
*
* Example: Annulus(radius=0.05, yheight=0.1)
*
* %P
* INPUT PARAMETERS:
* radius:  [m]     Outer radius of geometry in (x,z) plane
* xwidth:  [m]     Horiz. dimension of geometry
* yheight: [m]     Vert. dimensuon of geometry
* zdepth:  [m]     Depth dimension of geometry
* nx:      [1]     x-comp of orientation vector
* ny:      [1]     y-comp of orientation vector
* nz:      [1]     z-comp of orientation vector
*
* %L
* mcdoc page of <a href="Shape.html">Shape</a></b> component
*
* %E
*******************************************************************************/

DEFINE COMPONENT Disc

SETTING PARAMETERS (radius=0, xwidth=0, yheight=0, zdepth=0, nx=0, ny=1, nz=0)

/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */

SHARE
%{
%}

DECLARE
%{
%}

INITIALIZE
%{
  /* */
%}


TRACE %{
  /* component Disc does nothing */
%}

MCDISPLAY
%{
    mcdis_disc(0,0,0,radius, nx,ny,nz);
%}

END
