/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright (C) 1997-2017, All rights reserved
*         DTU Physics, Kgs. Lyngby, Denmark
*
* Component: KDSource
*
* %I
* Written by: Osiris I Abbate, Norberto S Schmidt
* Date: Dec 2022
* Origin: Instituto Balseiro
*
* Distributional source, based on a MCPL-format particle list, on which
* the Kernel Density Estimation (KDE) method is applied.
*
* %D
* Distributional source, based on a MCPL-format particle list, on which
* the Kernel Density Estimation (KDE) method is applied.
* 
* It allows sampling more particles than the number present in a virtual,
* previously generated virtual source, without repeating samples.
* 
* It requires a XML parameters file containing the needed configurations
* for an optimized KDE source, which can be generated with the KDSource
* package.
*
* When used with MPI, the --ncount given on the commandline is overwritten by 
* #MPI nodes x #events in the file.
*
* Example: KDSource("optimized_source.xml")
*
* %VALIDATION
*
* %BUGS
*
* %P
* INPUT PARAMETERS:
*
* filename: [str]       Name of the XML parameters file containing KDSource definition.
* use_kde    [0/1]      Whether to use KDE or just sample particles from the MCPL file. Default: 1
* verbose: [ ]          Print debugging information for first 10 particles read.
* polarisationuse: [ ]  If !=0 read polarisation vectors from file.
* Emin: [meV]           Lower energy bound. Particles found in the MCPL-file below the limit are skipped.
* Emax: [meV]           Upper energy bound. Particles found in the MCPL-file above the limit are skipped.
*
* %D
* Example values:
*
* %E
*******************************************************************************/

DEFINE COMPONENT KDSource
DEFINITION PARAMETERS ()
SETTING PARAMETERS (string filename=0, polarisationuse=0, verbose=0, Emin=0, Emax=FLT_MAX, use_kde=1)
OUTPUT PARAMETERS ()
/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */ 
DEPENDENCY " @MCPLFLAGS@ CMD(kdsource-config --show buildflags) "

SHARE
%{
#include "mcpl.h"
#include "kdsource/kdsource.h"
%}

DECLARE
%{
long long nparticles;
long long read_neutrons;
long long used_neutrons;
int inactive;
int mpi_cnt;

int N;
double I;
double p2;

KDSource *kdsource;
double w_crit;
double p_mul;
%}

INITIALIZE
%{
    char line[256];
    long long ncount=mcget_ncount();

    if (filename && strlen(filename) && strcmp(filename, "NULL") && strcmp(filename,"0")) {
      /* We got a proper filename, do the rest of the work */
    inactive=0;
    if(Emax<Emin){
        fprintf(stderr,"Warning(%s): Nonsensical energy interval: E=[%g,%g]. Aborting.\n",NAME_CURRENT_COMP,Emin,Emax);
        exit(-1);
    }
    /* No need to check if the file opens correctly since mcpl will
     * abort internally if it cannot open the file.*/
    kdsource = KDS_open(filename);

    MPI_MASTER(
      if ( !(nparticles=kdsource->plist->npts) ) {
        fprintf(stderr,"Warning(%s): MCPL-file reports no present particles. Foolishly trying to go on.\n",NAME_CURRENT_COMP);
        exit(-1);
      }else{
        printf("Message(%s): MCPL file called in the %s file contains %lu particles.\n",NAME_CURRENT_COMP,filename,(long unsigned)nparticles); 
      }
    );
    
    w_crit = use_kde ? KDS_w_mean(kdsource, 1000, NULL): -1;
    read_neutrons=0;
    used_neutrons=0;
    
    MPI_MASTER(
      if (verbose==1) {
        printf("KDSource verbose mode - outputting data on the 10 first read neutrons in MCPL units:\n");
      }
    );
    } else {
      /* Not presented with a reasonable filename, skip further action */
      inactive=1;
      printf("%s: filename is NULL or empty, skipping init and reads\n", NAME_CURRENT_COMP);
    }
    p_mul=(double)nparticles/(double)ncount;
%}

TRACE
%{
  long long ncount;
  int eof_reached;

  double nrm;
  mcpl_particle_t part;
  if(!inactive) {
    eof_reached = KDS_sample2(kdsource, &part, use_kde, w_crit, NULL, 1);

    ncount=mcget_ncount();
    if (part.pdgcode!=2112) {
        /*Either no particle read, particle is not a neutron, or it has invalid energy - terminate to trigger next ray*/
       ABSORB;
    }
    read_neutrons++;
    
    /* check energy range*/
    if ( part.ekin<Emin*1e-9 || part.ekin>Emax*1e-9 ) {
        /*Particle energy out of range - terminate to trigger next ray*/
        ABSORB;
    }
    used_neutrons++;

    MPI_MASTER(
	       if (verbose && used_neutrons<11) {
		 printf("id=%lu pdg=2112\tekin=%g MeV\tx=%g cm\ty=%g cm\tz=%g cm\tux=%g\tuy=%g\tuz=%g\tt=%g ms\tweight=%g\tpolx=%g\tpoly=%g\tpolz=%g\n",
			(long unsigned)read_neutrons, part.ekin, part.position[0], part.position[1], part.position[2],
			part.direction[0], part.direction[1], part.direction[2], part.time, part.weight,
			part.polarisation[0], part.polarisation[1], part.polarisation[2]);
	       }
	       );

    /*positions are in cm*/
    x=part.position[0]/100;
    y=part.position[1]/100;
    z=part.position[2]/100;
    
    if(polarisationuse){
        sx=part.polarisation[0];
        sy=part.polarisation[1];
        sz=part.polarisation[2];
    }else{
        sx=sy=sz=0;
    }

    nrm = part.ekin *1e9/VS2E;
    nrm = sqrt(nrm);
    double d0=part.direction[0],d1=part.direction[1],d2=part.direction[2];
    
    vx=d0*nrm;
    vy=d1*nrm;
    vz=d2*nrm;   

    /*time in ms:*/
    t=part.time*1e-3;
    /*weight in unspecified units:*/
    p=part.weight;
    p*=p_mul;
    I += p;
    p2 += p*p;
    N++;
    SCATTER;
  }
%}

SAVE
%{
  MPI_MASTER(
    printf("KDSource %s: I err N %lf %lf %d\n", NAME_CURRENT_COMP, I, sqrt(p2), N);
  )
%}

FINALLY
%{
  if(!inactive) {
    long long ncount;

    ncount=mcget_ncount();

    if (used_neutrons!=read_neutrons){
        fprintf(stdout,"Message(%s): You have used %lu of %lu neutrons available in the MCPL file.\n",NAME_CURRENT_COMP,
          (long unsigned)used_neutrons,(long unsigned)read_neutrons);
    }
    if (ncount != used_neutrons){
        fprintf(stderr,"Warning (%s): You requested %lu neutrons from a file which contains %lu particles in general, of which only %lu are neutrons (within the wanted energy interval).\n"
                "Please examine the recorded intensities carefully.\n",
          NAME_CURRENT_COMP,(long unsigned)ncount,(long unsigned)nparticles,(long unsigned)used_neutrons);
    }
  }
%}

MCDISPLAY
%{


/* K at x = -0.9 */
line(-0.95,-0.5,0, -0.95,0.5,0);
line(-0.95,0.0,0, -0.65,0.48,0);
line(-0.95,0.0,0, -0.65,0.42,0);
line(-0.95,0.0,0, -0.65,0.36,0);
line(-0.95,0.0,0, -0.65,0.30,0);
line(-0.95,0.0,0, -0.65,0.18,0);
line(-0.95,0.0,0, -0.65,0.06,0);
line(-0.95,0.0,0, -0.65,-0.06,0);
line(-0.95,0.0,0, -0.65,-0.18,0);
line(-0.95,0.0,0, -0.65,-0.30,0);
line(-0.95,0.0,0, -0.65,-0.36,0);
line(-0.95,0.0,0, -0.65,-0.42,0);
line(-0.95,0.0,0, -0.65,-0.48,0);


/* D at x = 0.0 */
line(-0.05,-0.5,0, -0.05,0.5,0);
line(-0.05,0.5,0, -0.013,0.496,0);
line(-0.013,0.496,0, 0.030,0.485,0);
line(0.030,0.485,0, 0.072,0.467,0);
line(0.072,0.467,0, 0.113,0.442,0);
line(0.113,0.442,0, 0.151,0.411,0);
line(0.151,0.411,0, 0.185,0.375,0);
line(0.185,0.375,0, 0.214,0.334,0);
line(0.214,0.334,0, 0.237,0.289,0);
line(0.237,0.289,0, 0.253,0.241,0);
line(0.253,0.241,0, 0.263,0.191,0);
line(0.263,0.191,0, 0.266,0.140,0);
line(0.266,0.140,0, 0.263,0.088,0);
line(0.263,0.088,0, 0.253,0.036,0);
line(0.253,0.036,0, 0.237,-0.016,0);
line(0.237,-0.016,0, 0.214,-0.067,0);
line(0.214,-0.067,0, 0.185,-0.117,0);
line(0.185,-0.117,0, 0.151,-0.164,0);
line(0.151,-0.164,0, 0.113,-0.209,0);
line(0.113,-0.209,0, 0.072,-0.250,0);
line(0.072,-0.250,0, 0.030,-0.287,0);
line(0.030,-0.287,0, -0.013,-0.318,0);
line(-0.013,-0.318,0, -0.05,-0.34,0);
line(-0.05,-0.34,0, -0.05,-0.5,0);


/* S at x = 0.9 */
line(1.25,0.45,0, 1.15,0.48,0);
line(1.15,0.48,0, 1.03,0.50,0);
line(1.03,0.50,0, 0.90,0.49,0);
line(0.90,0.49,0, 0.78,0.44,0);
line(0.78,0.44,0, 0.68,0.36,0);
line(0.68,0.36,0, 0.60,0.26,0);
line(0.60,0.26,0, 0.56,0.15,0);
line(0.56,0.15,0, 0.58,0.03,0);
line(0.58,0.03,0, 0.66,-0.07,0);
line(0.66,-0.07,0, 0.80,-0.14,0);
line(0.80,-0.14,0, 0.95,-0.22,0);
line(0.95,-0.22,0, 1.07,-0.30,0);
line(1.07,-0.30,0, 1.15,-0.38,0);
line(1.15,-0.38,0, 1.20,-0.45,0);
line(1.20,-0.45,0, 1.22,-0.48,0);
%}

END
