/*******************************************************************************
*
* McStas, neutron ray-tracing package
*         Copyright (C) 1997-2017, All rights reserved
*         DTU Physics, Kgs. Lyngby, Denmark
*
* Component: KDSource
*
* %I
* Written by: Osiris I Abbate, Norberto S Schmidt
* Date: Dec 2022
* Origin: Instituto Balseiro
*
* Distributional source, based on a MCPL-format particle list, on which
* the Kernel Density Estimation (KDE) method is applied.
*
* %D
* TODO: UPDATE DESCRIPTION AND OTHER METADATA
* Distributional source, based on a MCPL-format particle list, on which
* the Kernel Density Estimation (KDE) method is applied.
*
* It allows sampling more particles than the number present in a virtual,
* previously generated virtual source, without repeating samples.
*
* It requires a XML parameters file containing the needed configurations
* for an optimized KDE source, which can be generated with the KDSource
* package.
*
* When used with MPI, the --ncount given on the commandline is overwritten by
* #MPI nodes x #events in the file.
*
* Example: KDSource("optimized_source.xml")
*
* %VALIDATION
*
* %BUGS
*
* %P
* INPUT PARAMETERS:
*
* filename: [str]       Name of the XML parameters file containing KDSource definition.
* verbose: [ ]          Print debugging information for first 10 particles read.
* polarisationuse: [ ]  If !=0 read polarisation vectors from file.
* Emin: [meV]           Lower energy bound. Particles found in the MCPL-file below the limit are skipped.
* Emax: [meV]           Upper energy bound. Particles found in the MCPL-file above the limit are skipped.
* nloop [int]: Number of times to loop through the file.
*
* %D
* Example values:
*
* %E
*******************************************************************************/

DEFINE COMPONENT KDSource
SETTING PARAMETERS (string filename=0, int polarisationuse=0, Emin=0, Emax=FLT_MAX, int nloop = 1 )

/* Neutron parameters: (x,y,z,vx,vy,vz,t,sx,sy,sz,p) */
DEPENDENCY " @MCPLFLAGS@ CMD(kdsource-config --show buildflags) "
NOACC

SHARE
%{
#include "mcpl.h"
#include "kdsource/kdsource.h"


uint64_t kds_ncount( uint64_t iproc, uint64_t nprocs, uint64_t nloop, uint64_t nfile)
{
  uint64_t ntot = nloop * nfile;
  uint64_t n = ntot / nprocs;
  uint64_t nextra = ntot-n*nprocs;
  return ( iproc < nextra ? (n+1) : n );
}

uint64_t kds_nskip(uint64_t iproc, uint64_t nprocs, uint64_t nloop, uint64_t nfile )
{
 uint64_t nskip = 0;
 for ( uint64_t i = 0; i < iproc; ++i )
   nskip += kds_ncount(i,nprocs,nloop,nfile);
 return nskip % nfile;
}



%}

DECLARE
%{
/*TODO: polarisationuse should be autodetected*/

/* long long nparticles; */
/* long long read_neutrons; */
/* long long used_neutrons; */
/* int inactive; */
/* int mpi_cnt; */

/* int N; */
/* double I; */
/* double p2; */

KDSource *kdsource;
/* double w_crit; */
/* double p_mul; */
double weight_scale;
int use_polarisation;
%}

INITIALIZE
%{
    /* inactive=0; */
    if(Emax<Emin){
      fprintf(stderr,"Warning(%s): Nonsensical energy interval: E=[%g,%g]. Aborting.\n",NAME_CURRENT_COMP,Emin,Emax);
      exit(-1);
    }
    //meV to MeV
    Emin *= 1e-9;
    Emax *= 1e-9;


    /* NB: KDSource will abort if it can not open the file*/
    kdsource = KDS_open(filename);

    use_polarisation = mcpl_hdr_has_polarisation(kdsource->plist->file);

    const uint64_t npts = (uint64_t)kdsource->plist->npts;
#ifdef USE_MPI
    const uint64_t nprocs = (uint64_t)mpi_node_count;
    const uint64_t iproc = (uint64_t)mpi_node_rank;
#else
    const uint64_t nprocs = 1;
    const uint64_t iproc = 0;
#endif
    uint64_t ncount =  kds_ncount( iproc, nprocs, (uint64_t)nloop, npts);
    uint64_t nskip = kds_nskip( iproc, nprocs, (uint64_t)nloop, npts);

    weight_scale = 1.0 / nloop;//preserve sum of weights in mcpl file,
                               //independent of nloop.


    char filenamefoo[320];

    snprintf(filenamefoo, sizeof filenamefoo, "test%i.txt", (int)iproc);

    mcset_ncount(ncount*nprocs);
    if ( nskip && !mcpl_seek(kdsource->plist->file,nskip)) {
      fprintf(stderr,"ERROR(%s): Could not seek ahead in MCPL file.\n",NAME_CURRENT_COMP);
      exit(-1);
    }
%}

TRACE
%{
  double nrm;
  mcpl_particle_t part;
  KDS_sample2(kdsource, &part, 1, -1.0, NULL, 1);

#ifdef USE_MPI
    const uint64_t iproc = (uint64_t)mpi_node_rank;
#else
    const uint64_t iproc = 0;
#endif
  if (part.pdgcode!=2112) {
    /*Either no particle read, particle is not a neutron, or it has invalid energy - terminate to trigger next ray*/
    ABSORB;
  }
  /* read_neutrons++; */

  /* check energy range*/
  if ( part.ekin<Emin || part.ekin>Emax ) {
    /*Particle energy out of range - terminate to trigger next ray*/
    ABSORB;
  }

  /*positions are in cm*/
  x=part.position[0]*0.01;
  y=part.position[1]*0.01;
  z=part.position[2]*0.01;

  if(use_polarisation){
    sx=part.polarisation[0];
    sy=part.polarisation[1];
    sz=part.polarisation[2];
  }else{
    sx=sy=sz=0;
  }

  nrm = sqrt( part.ekin *1e9/VS2E );
  double d0=part.direction[0],d1=part.direction[1],d2=part.direction[2];

  vx=part.direction[0]*nrm;
  vy=part.direction[1]*nrm;
  vz=part.direction[2]*nrm;

  /*time in ms:*/
  t=part.time*1e-3;
  /*weight in unspecified units:*/
  p = part.weight * weight_scale;
  SCATTER;
%}

SAVE
%{
%}

FINALLY
%{
  KDS_destroy(kdsource);
%}

MCDISPLAY
%{


  /* K at x = -0.9 */
  line(-0.95,-0.5,0, -0.95,0.5,0);
  line(-0.95,0.0,0, -0.65,0.48,0);
  line(-0.95,0.0,0, -0.65,0.42,0);
  line(-0.95,0.0,0, -0.65,0.36,0);
  line(-0.95,0.0,0, -0.65,0.30,0);
  line(-0.95,0.0,0, -0.65,0.18,0);
  line(-0.95,0.0,0, -0.65,0.06,0);
  line(-0.95,0.0,0, -0.65,-0.06,0);
  line(-0.95,0.0,0, -0.65,-0.18,0);
  line(-0.95,0.0,0, -0.65,-0.30,0);
  line(-0.95,0.0,0, -0.65,-0.36,0);
  line(-0.95,0.0,0, -0.65,-0.42,0);
  line(-0.95,0.0,0, -0.65,-0.48,0);


  /* D at x = 0.0 */
  line(-0.05,-0.5,0, -0.05,0.5,0);
  line(-0.05,0.5,0, -0.013,0.496,0);
  line(-0.013,0.496,0, 0.030,0.485,0);
  line(0.030,0.485,0, 0.072,0.467,0);
  line(0.072,0.467,0, 0.113,0.442,0);
  line(0.113,0.442,0, 0.151,0.411,0);
  line(0.151,0.411,0, 0.185,0.375,0);
  line(0.185,0.375,0, 0.214,0.334,0);
  line(0.214,0.334,0, 0.237,0.289,0);
  line(0.237,0.289,0, 0.253,0.241,0);
  line(0.253,0.241,0, 0.263,0.191,0);
  line(0.263,0.191,0, 0.266,0.140,0);
  line(0.266,0.140,0, 0.263,0.088,0);
  line(0.263,0.088,0, 0.253,0.036,0);
  line(0.253,0.036,0, 0.237,-0.016,0);
  line(0.237,-0.016,0, 0.214,-0.067,0);
  line(0.214,-0.067,0, 0.185,-0.117,0);
  line(0.185,-0.117,0, 0.151,-0.164,0);
  line(0.151,-0.164,0, 0.113,-0.209,0);
  line(0.113,-0.209,0, 0.072,-0.250,0);
  line(0.072,-0.250,0, 0.030,-0.287,0);
  line(0.030,-0.287,0, -0.013,-0.318,0);
  line(-0.013,-0.318,0, -0.05,-0.34,0);
  line(-0.05,-0.34,0, -0.05,-0.5,0);


  /* S at x = 0.9 */
  line(1.25,0.45,0, 1.15,0.48,0);
  line(1.15,0.48,0, 1.03,0.50,0);
  line(1.03,0.50,0, 0.90,0.49,0);
  line(0.90,0.49,0, 0.78,0.44,0);
  line(0.78,0.44,0, 0.68,0.36,0);
  line(0.68,0.36,0, 0.60,0.26,0);
  line(0.60,0.26,0, 0.56,0.15,0);
  line(0.56,0.15,0, 0.58,0.03,0);
  line(0.58,0.03,0, 0.66,-0.07,0);
  line(0.66,-0.07,0, 0.80,-0.14,0);
  line(0.80,-0.14,0, 0.95,-0.22,0);
  line(0.95,-0.22,0, 1.07,-0.30,0);
  line(1.07,-0.30,0, 1.15,-0.38,0);
  line(1.15,-0.38,0, 1.20,-0.45,0);
  line(1.20,-0.45,0, 1.22,-0.48,0);
%}

END
