name: mcstas-basictest
on:
  push:
  pull_request:
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday

  workflow_dispatch:
    inputs:
      manual-debugging:
        type: boolean
        description: Launch manual debugging tmate for inspection (automatic in case of errors)
        default: false

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04,   CC: gcc-13,   CXX: g++-13,     python: '3.12', mpi: 'openmpi' }
          - { os: ubuntu-24.04,   CC: clang,    CXX: clang++,    python: '3.12', mpi: 'openmpi' }
          - { os: ubuntu-22.04,   CC: clang,    CXX: clang++,    python: '3.11', mpi: 'openmpi' }
          - { os: ubuntu-22.04,   CC: gcc-12,   CXX: g++-12,     python: '3.11', mpi: 'openmpi' }
          - { os: macos-13,       CC: clang,    CXX: clang++,    python: "3.11", mpi: 'mpich'   }
          - { os: macos-14,       CC: clang,    CXX: clang++,    python: "3.12", mpi: 'mpich'   }
          - { os: macos-15,       CC: clang,    CXX: clang++,    python: "3.13", mpi: 'mpich'   }
          - { os: windows-2022,   CC: cl.exe,   CXX: cl.exe,     python: "3.13", mpi: 'msmpi'   }
          - { os: windows-2022,   CC: gcc.exe,  CXX: g++.exe,    python: "3.13", mpi: 'msmpi'   }
          - { os: windows-2025,   CC: cl.exe,   CXX: cl.exe,     python: "3.13", mpi: 'msmpi'   }
          - { os: windows-11-arm, CC: cl.exe,   CXX: cl.exe,     python: "3.13", mpi: 'msmpi'   }

    name: ${{ matrix.os }}.${{ matrix.CC }}.${{ matrix.mpi }}.python-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        path: src
        fetch-depth: 2

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Setup VS in shell Intel
      if: runner.os == 'Windows' && matrix.os != 'windows-11-arm'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup VS in shell arm64
      if: runner.os == 'Windows' && matrix.os == 'windows-11-arm'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: arm64

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}

    - name: Setup (Linux)
      id: setup-linux
      if: runner.os == 'Linux'
      run: |
           echo No dependencies needed here

    - name: Setup (macOS)
      id: setup-macos
      if: runner.os == 'macOS'
      run: |
           brew install bison flex gfortran gsl

    - name: Setup (Windows)
      id: setup-Windows
      if: runner.os == 'Windows'
      shell: bash
      run:   |
        cygpath -sm "$MSMPI_INC" > includepath.txt
        cygpath -sm "$MSMPI_LIB64" > libpath.txt
        choco install winflexbison3
        choco install wget
        if [ "$CC" == "gcc.exe" ]; then choco install mingw; fi
        pip install mslex PyYAML ply ncrystal mcpl mcpl-extra

    - name: Setup (Windows Intel)
      id: setup-Windows-intel
      if: runner.os == 'Windows' && matrix.os !='windows-11-arm'
      shell: bash
      run:   |
        pip install McStasscript ncrystal

    - name: Setup MPI cygpath...
      id: setup-Windows-paths
      if: runner.os == 'Windows'
      run: |
        set /p MPIINCVAR=<includepath.txt
        set /p MPILIBVAR=<libpath.txt
        echo MPIINCVAR=%MPIINCVAR% >> %GITHUB_ENV%
        echo MPILIBVAR=%MPILIBVAR% >> %GITHUB_ENV%

    - name: Check versions
      id: version-checks
      run: |
           which python3
           python3 --version
           which cmake
           cmake --version

    - name: Configure build and install mcstas on Unix
      id: mcstas-install-unix
      if: runner.os != 'Windows'
      run: |
           if [ "$RUNNER_OS" == "macOS" ]; then mkdir ${HOME}/tmp; fi
           if [ "$RUNNER_OS" == "macOS" ]; then export SDKROOT=$(xcrun --sdk macosx --show-sdk-path); fi
           set -e
           set -u
           set -x
           mkdir build_mcstas
           cd build_mcstas
           export EXTRA_ARGS_FOR_CMAKE=""
           if [ "$RUNNER_OS" == "macOS" ] && [ -f "/opt/homebrew/opt/flex/bin/flex" ]; then export HOMEBRW="/opt/homebrew/opt"; export GSLFLAGS="-lgsl -lgslcblas -L/opt/homebrew/lib -I/opt/homebrew/include"; fi
           if [ "$RUNNER_OS" == "macOS" ] && [ -f "/usr/local/opt/flex/bin/flex" ]; then export HOMEBRW="/usr/local/opt"; export GSLFLAGS="-lgsl -lgslcblas -L/usr/local/lib -I/usr/local/include"; fi
           if [ "$RUNNER_OS" == "macOS" ]; then export EXTRA_ARGS_FOR_CMAKE="-DBISON_EXECUTABLE=${HOMEBRW}/bison/bin/bison -DFLEX_EXECUTABLE=${HOMEBRW}/flex/bin/flex -DCMAKE_Fortran_COMPILER=${HOMEBRW}/gfortran/bin/gfortran"; fi
           if [ "$RUNNER_OS" == "Linux" ]; then export EXTRA_ARGS_FOR_CMAKE="-DNEXUSLIB=/usr/lib -DNEXUSINCLUDE=/usr/include/nexus"; fi
           if [ "$RUNNER_OS" == "Windows" ]; then export MPIINC=`cygpath -m -s  "${MSMPI_INC}"`; export MPILIB=`cygpath -m -s  "${MSMPI_LIB64}"`; export EXTRA_ARGS_FOR_CMAKE="-DMPILIBDIR=${MPILIB} -DMPIINCLUDEDIR=${MPIINC}"; fi
           cmake \
               -DCMAKE_INSTALL_PREFIX=../install_mcstas \
               -S ../src \
               -G "Unix Makefiles" \
               -DMCVERSION="3.99.99" \
               -DMCCODE_BUILD_CONDA_PKG=OFF \
               -DBUILD_SHARED_LIBS=ON \
               -DCMAKE_INSTALL_LIBDIR=lib \
               -DCMAKE_BUILD_TYPE=Release \
               -DBUILD_MCSTAS=ON \
               -DMCCODE_USE_LEGACY_DESTINATIONS=OFF \
               -DBUILD_TOOLS=ON \
               -DENABLE_COMPONENTS=ON \
               -DENSURE_MCPL=OFF \
               -DENSURE_NCRYSTAL=OFF \
               -DENABLE_CIF2HKL=ON \
               -DENABLE_NEUTRONICS=OFF \
               ${EXTRA_ARGS_FOR_CMAKE}
           cmake --build . --config Release
           cmake --build . --target install --config Release
           export MCSTAS_EXECUTABLE="mcstas"
           export MCRUN_EXECUTABLE="mcrun"
           if [ "$RUNNER_OS" == "Windows" ];
           then
             export MCSTAS_EXECUTABLE="mcstas.exe"
             export MCRUN_EXECUTABLE="mcrun.bat"
           fi
           test -f "../install_mcstas/bin/${MCSTAS_EXECUTABLE}"
           test -f "../install_mcstas/bin/${MCRUN_EXECUTABLE}"
           test -f "../install_mcstas/share/mcstas/tools/Python/mccodelib/__init__.py"
           test -d "../install_mcstas/share/mcstas/resources/data"
           if [ "${{ matrix.mpi }}" == "openmpi" ]; then sed -i.bak 's/mpirun/mpirun\ --verbose\ --mca\ btl\ self,vader,tcp/g' ../install_mcstas/share/mcstas/tools/Python/mccodelib/mccode_config.json ; fi
           if [ "$RUNNER_OS" == "macOS" ]; then sed -i.bak "s+-lgsl\ -lgslcblas+${GSLFLAGS}+g" ../install_mcstas/share/mcstas/tools/Python/mccodelib/mccode_config.json ; fi
           echo *******************************************************************************
           echo Resulting mccode_config.json:
           echo *******************************************************************************
           cat ../install_mcstas/share/mcstas/tools/Python/mccodelib/mccode_config.json
           echo *******************************************************************************

    - name: Configure build and install mcstas on Windows-Mingw
      id: mcstas-install-windows-mingw
      if: ${{ matrix.CC == 'gcc.exe' && runner.os == 'Windows' }}
      run: >
        cmake -B build -S src
        -G "Unix Makefiles"
        -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc.exe
        "-DCMAKE_INSTALL_PREFIX=./install"
        -DMCVERSION="3.99.99"
        -DMCCODE_BUILD_CONDA_PKG=OFF
        -DMCCODE_BUILD_WINDOWS_MINGW=ON
        -DMCCODE_CONFIG_MCPL2=ON
        -DCMAKE_INSTALL_LIBDIR=lib
        -DBUILD_MCSTAS=ON
        -DMCCODE_USE_LEGACY_DESTINATIONS=OFF
        -DBUILD_TOOLS=ON
        -DENABLE_COMPONENTS=ON
        -DENABLE_CIF2HKL=ON
        -DENABLE_NEUTRONICS=OFF
        -DMPIINCLUDEDIR=%MPIINCVAR%
        -DMPILIBDIR=%MPILIBVAR%

    - name: Configure build and install mcstas on Windows-MSVC
      id: mcstas-install-windows-msvc
      if: ${{ matrix.CC != 'gcc.exe' && runner.os == 'Windows' }}
      run: >
        cmake -B build -S src
        "-DCMAKE_INSTALL_PREFIX=./install"
        -DMCVERSION="3.99.99"
        -DMCCODE_BUILD_CONDA_PKG=OFF
        -DMCCODE_CONFIG_MCPL2=ON
        -DCMAKE_INSTALL_LIBDIR=lib
        -DBUILD_MCSTAS=ON
        -DMCCODE_USE_LEGACY_DESTINATIONS=OFF
        -DBUILD_TOOLS=ON
        -DENABLE_COMPONENTS=ON
        -DENABLE_CIF2HKL=OFF
        -DENABLE_NEUTRONICS=OFF
        -DMPIINCLUDEDIR=%MPIINCVAR%
        -DMPILIBDIR=%MPILIBVAR%

    - name: CMake build
      if: runner.os == 'Windows'
      shell: cmd
      run: cmake --build build --config Release -j 2

    - name: CMake install
      if: runner.os == 'Windows'
      run: cmake --install build --config Release

    - name: set MCSTAS env var
      if: runner.os == 'Windows'
      run: echo MCSTAS=%CD%\install\share\mcstas\resources >> %GITHUB_ENV%

    - name: check MCSTAS env var
      if: runner.os == 'Windows'
      run: echo %MCSTAS%

    - name: Various Windows debugging
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        type .\install\share\mcstas\tools\Python\mccodelib\mccode_config.json
        .\install\bin\mcrun -h
        .\install\bin\mcstas -v
        mcpl-config -s
        ncrystal-config -s

    # - name: 'Tar output files'
    #   id: tar-package
    #   if: always()
    #   run: |
    #        set -e
    #        set -u
    #        set -x
    #        tar cvfz mcstas-${{ matrix.os }}.${{ matrix.CC }}.${{ matrix.mpi }}.python-${{ matrix.python }}_output.tgz run_*

    # - name: 'Upload Artifact'
    #   id: tar-upload
    #   uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: mcstas-artefacts-${{ matrix.os }}.${{ matrix.CC }}.${{ matrix.mpi }}.python-${{ matrix.python }}
    #     path: "mcstas-${{ matrix.os }}.${{ matrix.CC }}.${{ matrix.mpi }}.python-${{ matrix.python }}_output.tgz"

    - name: Setup tmate session for manual debugging
      uses: mxschmitt/action-tmate@v3
      if: always() && (inputs.manual-debugging == true)
      with:
        limit-access-to-actor: true
